apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: general-insurance
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: general-insurance
      server: https://kubernetes.default.svc
  sourceRepos:
    - {{ .Values.spec.apps.ecsdemoNodejs.repoURL }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: general-insurance
  namespace: argocd
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: general-insurance
  destination:
    namespace: general-insurance
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.ecsdemoNodejs.repoURL }}
    targetRevision: {{ .Values.spec.apps.ecsdemoNodejs.targetRevision }}
    path: {{ .Values.spec.apps.ecsdemoNodejs.path }}
    helm:
      parameters:
        - name: replicaCount
          value: '3'    
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # Created with IaC - # https://github.com/argoproj/argo-cd/issues/7799
